version: '3.7'
services:
  mongo-seed:
    build: .
    depends_on:
      - mongodb_container

  mongodb_container:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db

volumes:
  mongodb_data_container:
